# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-KKQpB8HHUMZ9mNpGETAQhsc1t-Lzg2r
"""

!pip install -q langchain langgraph langchain-community langchain-core
!pip install -q pypdf python-dotenv
!pip install -q groq langchain_openai

import os
os.environ["GROQ_API_KEY"] = "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"

from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model="llama-3.3-70b-versatile",
    openai_api_key=os.environ["GROQ_API_KEY"],
    base_url="https://api.groq.com/openai/v1",
    temperature=0
)

print("LLM Ready")

SYSTEM_PROMPT = """
You are a document processing specialist.

Tasks:
1. Classify document:
   - Cease
   - Irrelevant
   - Uncertain

2. Extract:
   - Name
   - Date
   - Request reason

3. Provide confidence score.

Rules:
- Be precise
- If unclear → Uncertain
- Maintain structured output
"""

from google.colab import files

uploaded = files.upload()

import os

os.listdir("/content")

from pypdf import PdfReader

def load_document(file_path):
    reader = PdfReader(file_path)
    text = ""

    for page in reader.pages:
        text += page.extract_text() or ""

    return text

def process_all_documents():

    import os

    pdf_files = [f for f in os.listdir("/content") if f.endswith(".pdf")]

    print("Files detected:", pdf_files)

    for file in pdf_files:

        file_path = f"/content/{file}"

        process_all_document(file_path)

import json
import re

def extract_json_safe(text):

    try:
        return json.loads(text)

    except:
        match = re.search(r"\{.*\}", text, re.DOTALL)

        if match:
            try:
                return json.loads(match.group())
            except:
                return None

    return None

def classify_document(text):

    prompt = f"""
    You are a document classification expert.

    Classify this document into one of:
    - Cease
    - Irrelevant
    - Uncertain

    Return JSON only:

    {{
        "label": "",
        "confidence": 0,
        "reason": ""
    }}

    Document:
    {text}
    """

    response = llm.invoke(prompt).content

    return extract_json_safe(response)

def extract_information(text):

    prompt = f"""
    You are an expert document extraction system.

    Extract the following details.

    Return STRICT JSON ONLY:

    {{
        "name": null or string,
        "date": null or string,
        "reason": null or string,
        "contact": null or string
    }}

    Document:
    {text}
    """

    response = llm.invoke(prompt).content

    return extract_json_safe(response)

import sqlite3

conn = sqlite3.connect("cease_requests.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS cease_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    document_name TEXT,
    processed_date TEXT,
    extracted_data TEXT
)
""")

conn.commit()

print("Database created successfully")

def store_to_database(document_name, extracted_data):

    cursor.execute(
        "INSERT INTO cease_requests (document_name, processed_date, extracted_data) VALUES (?, datetime('now'), ?)",
        (document_name, json.dumps(extracted_data))
    )

    conn.commit()

def audit_log(action, document_name):

    with open("audit_log.txt", "a") as f:
        f.write(f"{action} : {document_name}\n")

def human_review(text):

    print("\n⚠️ HUMAN REVIEW REQUIRED")
    print(text[:500])

    decision = input("Enter decision (Cease / Irrelevant): ")

    return decision

from langgraph.graph import StateGraph

from typing import TypedDict

class State(TypedDict):
    text: str
    document_name: str
    classification: dict

def classify_node(state):

    # Safety check (so KeyError will never happen again)
    if "text" not in state:
        print("ERROR: text not found in state")
        print("State received:", state)
        return state

    result = classify_document(state["text"])

    if result is None:
        result = {
            "label": "Uncertain",
            "confidence": 0,
            "reason": "Parsing failed"
        }

    state["classification"] = result

    return state


def route_node(state):

    label = state["classification"]["label"]

    if label == "Cease":
        return "cease"

    elif label == "Irrelevant":
        return "irrelevant"

    else:
        return "uncertain"


def cease_node(state):

    extracted_data = extract_information(state["text"])

    store_to_database(state["document_name"], extracted_data)

    audit_log("CEASE_DOCUMENT", state["document_name"])

    print("Stored in DB:", state["document_name"])

    return state


def irrelevant_node(state):

    audit_log("IRRELEVANT_DOCUMENT", state["document_name"])

    print("Irrelevant:", state["document_name"])

    return state


def uncertain_node(state):

    decision = human_review(state["text"])

    if decision == "Cease":
        return cease_node(state)
    else:
        return irrelevant_node(state)

graph = StateGraph(State)

graph.add_node("classify", classify_node)
graph.add_node("cease", cease_node)
graph.add_node("irrelevant", irrelevant_node)
graph.add_node("uncertain", uncertain_node)

graph.set_entry_point("classify")

graph.add_conditional_edges(
    "classify",
    route_node,
    {
        "cease": "cease",
        "irrelevant": "irrelevant",
        "uncertain": "uncertain"
    }
)

app = graph.compile()

print("LangGraph Ready")

import os

def process_single_document(file_path):

    # Step 1: Load text from PDF
    text = load_document(file_path)

    # Step 2: Extract file name
    doc_name = os.path.basename(file_path)

    # Step 3: Create correct state (VERY IMPORTANT)
    state = {
        "text": text,
        "document_name": doc_name
    }

    # Step 4: Run LangGraph
    app.invoke(state)

    print("Completed:", doc_name)

import os

def process_all_documents():

    pdf_files = [f for f in os.listdir("/content") if f.endswith(".pdf")]

    print("Files detected:", pdf_files)

    for file in pdf_files:

        file_path = f"/content/{file}"

        print("\nProcessing:", file)

        # Step 1: Read PDF
        text = load_document(file_path)

        # Step 2: Create proper state
        state = {
            "text": text,
            "document_name": file
        }

        print("State created successfully")

        # Step 3: Run graph correctly
        app.invoke(state)

        print("Completed:", file)

app = graph.compile()

process_all_documents()

cursor.execute("SELECT * FROM cease_requests")

rows = cursor.fetchall()

for row in rows:
    print(row)